[features]
seeds = false
skip-lint = false
[programs.devnet]
pnft = "HPmsRXtcs41XciPbjRztDPrm8cCki7E6h7DxCQSaRdMv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/work/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
